import { MenuItem, DietaryTag, Badge, PromoCode, GalleryImage, TeamMember, Reservation } from './types';

export const MENU_CATEGORIES = ['Loaded Fries', 'Sides', 'Dips', 'Drinks'];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
    {
        id: 'lf-01',
        name: 'Classic Cheesy Fries',
        description: 'Crispy golden fries smothered in our signature three-cheese sauce and topped with fresh chives.',
        price: 8.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/cheesyfries/600/400',
        rating: 4.5,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Bacon Bits', price: 1.50 }, { name: 'Extra Cheese', price: 2.00 }, { name: 'Add Jalapeños', price: 0.75 }],
        reviews: [{ author: 'FryFanatic', rating: 5, comment: 'The best cheesy fries in town!' }],
        nutrition: { calories: 650, protein: 15, carbs: 70, fat: 35 }
    },
    {
        id: 'lf-02',
        name: 'Spicy Volcano Fries',
        description: 'A fiery eruption of flavor! Fries topped with spicy chili, jalapeños, pepper jack cheese, and a drizzle of sriracha aioli.',
        price: 10.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/volcanofries/600/400',
        rating: 4.8,
        dietaryTags: [],
        isSpicy: true,
        isAvailable: true,
        customizations: [{ name: 'Extra Chili', price: 2.50 }, { name: 'Sour Cream', price: 1.00 }],
        reviews: [{ author: 'HeatSeeker', rating: 5, comment: 'Perfectly spicy and delicious!' }],
        nutrition: { calories: 800, protein: 25, carbs: 75, fat: 45 }
    },
    {
        id: 'lf-03',
        name: 'Vegan Garden Delight',
        description: 'A healthy and hearty option. Sweet potato fries topped with black beans, corn salsa, avocado, and a cilantro-lime vegan crema.',
        price: 11.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/veganfries/600/400',
        rating: 4.7,
        dietaryTags: [DietaryTag.Vegan, DietaryTag.GlutenFree, DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Vegan Chorizo', price: 3.00 }, { name: 'Extra Avocado', price: 2.00 }],
        reviews: [{ author: 'PlantPower', rating: 5, comment: 'So fresh and flavorful!' }],
        nutrition: { calories: 550, protein: 12, carbs: 80, fat: 20 }
    },
    {
        id: 'lf-04',
        name: 'BBQ Pulled Pork Fries',
        description: 'Slow-smoked pulled pork, tangy BBQ sauce, and creamy coleslaw piled high on our signature crispy fries.',
        price: 12.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/bbqporkfries/600/400',
        rating: 4.9,
        dietaryTags: [],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Pickles', price: 0.50 }, { name: 'Extra BBQ Sauce', price: 0.75 }],
        reviews: [{ author: 'BBQKing', rating: 5, comment: 'The pork is so tender!' }],
        nutrition: { calories: 950, protein: 30, carbs: 85, fat: 55 }
    },
    {
        id: 'lf-05',
        name: 'Mediterranean Delight Fries',
        description: 'A refreshing taste of the Mediterranean! Crispy fries topped with feta cheese, Kalamata olives, cherry tomatoes, cucumber, and a cool tzatziki sauce.',
        price: 11.50,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/medifries/600/400',
        rating: 4.6,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Grilled Chicken', price: 3.50 }, { name: 'Extra Feta', price: 1.50 }],
        reviews: [{ author: 'HealthyEats', rating: 4, comment: 'So light and fresh for loaded fries.' }],
        nutrition: { calories: 600, protein: 18, carbs: 70, fat: 28 }
    },
    {
        id: 'lf-06',
        name: 'Poutine Supreme',
        description: 'A Canadian classic, perfected. Squeaky cheese curds and rich, savory gravy over our golden fries, topped with crispy bacon bits.',
        price: 11.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/poutine/600/400',
        rating: 4.8,
        dietaryTags: [],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Fried Egg', price: 1.50 }, { name: 'Extra Gravy', price: 1.00 }],
        reviews: [{ author: 'CanuckFoodie', rating: 5, comment: 'The real deal! Best poutine this side of the border.' }],
        nutrition: { calories: 850, protein: 28, carbs: 72, fat: 50 }
    },
    {
        id: 'lf-07',
        name: 'Truffle Parmesan Fries',
        description: 'An elegant treat. Our fries tossed in aromatic truffle oil, generously dusted with grated Parmesan cheese, and garnished with fresh parsley.',
        price: 9.99,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/trufflefries/600/400',
        rating: 4.7,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Garlic Aioli Dip', price: 1.50 }],
        reviews: [{ author: 'GourmetGal', rating: 5, comment: 'Incredibly addictive flavor!' }],
        nutrition: { calories: 580, protein: 14, carbs: 65, fat: 30 }
    },
    {
        id: 'lf-08',
        name: 'Breakfast Anytime Fries',
        description: "Who says you can't have breakfast for dinner? Fries topped with fluffy scrambled eggs, crispy bacon, sausage gravy, and melted cheddar cheese.",
        price: 12.50,
        category: 'Loaded Fries',
        imageUrl: 'https://picsum.photos/seed/breakfastfries/600/400',
        rating: 4.5,
        dietaryTags: [],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Maple Syrup Drizzle', price: 1.00 }, { name: 'Make it spicy with Jalapeños', price: 0.75 }],
        reviews: [{ author: 'BrunchLover', rating: 5, comment: 'My two favorite meals in one!' }],
        nutrition: { calories: 1050, protein: 35, carbs: 78, fat: 65 }
    },
    {
        id: 'sd-01',
        name: 'Crispy Onion Rings',
        description: 'Golden, beer-battered onion rings served with your choice of dip.',
        price: 5.99,
        category: 'Sides',
        imageUrl: 'https://picsum.photos/seed/onionrings/600/400',
        rating: 4.3,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 400, protein: 5, carbs: 50, fat: 20 }
    },
    {
        id: 'sd-02',
        name: 'Sweet Potato Fries',
        description: 'A sweet and savory alternative. Naturally sweet potatoes fried to perfection, served with a side of chipotle aioli.',
        price: 6.50,
        category: 'Sides',
        imageUrl: 'https://picsum.photos/seed/sweetpotatofries/600/400',
        rating: 4.6,
        dietaryTags: [DietaryTag.Vegetarian, DietaryTag.GlutenFree],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 380, protein: 4, carbs: 55, fat: 18 }
    },
    {
        id: 'sd-03',
        name: 'Mozzarella Sticks',
        description: 'Classic, crispy, and cheesy. Six sticks of golden-fried mozzarella served with our zesty marinara sauce.',
        price: 7.99,
        category: 'Sides',
        imageUrl: 'https://picsum.photos/seed/mozzsticks/600/400',
        rating: 4.4,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 450, protein: 20, carbs: 35, fat: 25 }
    },
    {
        id: 'sd-04',
        name: 'Jalapeño Poppers',
        description: 'A spicy kick! Five jalapeños stuffed with cream cheese, breaded and fried until golden brown. Served with a side of ranch.',
        price: 7.50,
        category: 'Sides',
        imageUrl: 'https://picsum.photos/seed/poppers/600/400',
        rating: 4.7,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: true,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 400, protein: 10, carbs: 30, fat: 28 }
    },
    {
        id: 'dp-01',
        name: 'Garlic Aioli Dip',
        description: 'Creamy, dreamy, and packed with garlic. The perfect companion for any fry.',
        price: 1.50,
        category: 'Dips',
        imageUrl: 'https://picsum.photos/seed/garlicaioli/600/400',
        rating: 4.9,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 150, protein: 1, carbs: 2, fat: 15 }
    },
    {
        id: 'dp-02',
        name: 'House Ranch Dip',
        description: 'Our signature house-made ranch. Cool, creamy, and herby.',
        price: 1.25,
        category: 'Dips',
        imageUrl: 'https://picsum.photos/seed/ranchdip/600/400',
        rating: 4.5,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 120, protein: 1, carbs: 3, fat: 12 }
    },
    {
        id: 'dp-03',
        name: 'Honey Mustard Dip',
        description: 'The perfect balance of sweet and tangy. A classic favorite.',
        price: 1.25,
        category: 'Dips',
        imageUrl: 'https://picsum.photos/seed/honeymustard/600/400',
        rating: 4.6,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 100, protein: 1, carbs: 15, fat: 5 }
    },
    {
        id: 'dr-01',
        name: 'Fresh Lemonade',
        description: 'House-made lemonade, perfectly sweet and tart.',
        price: 3.50,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/lemonade/600/400',
        rating: 4.9,
        dietaryTags: [DietaryTag.Vegan, DietaryTag.GlutenFree, DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Strawberry Puree', price: 0.50 }, { name: 'Add Mint', price: 0.50 }],
        reviews: [],
        nutrition: { calories: 150, protein: 0, carbs: 40, fat: 0 }
    },
    {
        id: 'dr-02',
        name: 'Craft Root Beer',
        description: 'A rich and creamy root beer with notes of vanilla and sarsaparilla, made by a local brewery.',
        price: 4.00,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/rootbeer/600/400',
        rating: 4.8,
        dietaryTags: [DietaryTag.Vegan, DietaryTag.GlutenFree, DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Make it a float!', price: 2.00 }],
        reviews: [],
        nutrition: { calories: 180, protein: 0, carbs: 45, fat: 0 }
    },
    {
        id: 'dr-03',
        name: 'Classic Iced Tea',
        description: 'Freshly brewed black tea, served chilled over ice. Available sweet or unsweet.',
        price: 3.00,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/icedtea/600/400',
        rating: 4.4,
        dietaryTags: [DietaryTag.Vegan, DietaryTag.GlutenFree, DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Lemon', price: 0.25 }],
        reviews: [],
        nutrition: { calories: 90, protein: 0, carbs: 22, fat: 0 }
    },
    {
        id: 'dr-04',
        name: 'Strawberry Bliss Milkshake',
        description: 'A thick and creamy milkshake made with real strawberries and premium vanilla ice cream, topped with whipped cream.',
        price: 6.50,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/strawberryshake/600/400',
        rating: 4.9,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Extra Whipped Cream', price: 0.50 }],
        reviews: [],
        nutrition: { calories: 550, protein: 10, carbs: 80, fat: 20 }
    },
    {
        id: 'dr-05',
        name: 'Decadent Chocolate Milkshake',
        description: 'For the chocolate lovers! Rich chocolate syrup blended with premium ice cream for a smooth, indulgent treat.',
        price: 6.50,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/chocolateshake/600/400',
        rating: 4.8,
        dietaryTags: [DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [{ name: 'Add Malt', price: 0.75 }],
        reviews: [],
        nutrition: { calories: 580, protein: 11, carbs: 85, fat: 22 }
    },
    {
        id: 'dr-06',
        name: 'Classic Cola',
        description: 'The crisp, refreshing taste of classic cola on fountain.',
        price: 2.99,
        category: 'Drinks',
        imageUrl: 'https://picsum.photos/seed/cola/600/400',
        rating: 4.5,
        dietaryTags: [DietaryTag.Vegan, DietaryTag.GlutenFree, DietaryTag.Vegetarian],
        isSpicy: false,
        isAvailable: true,
        customizations: [],
        reviews: [],
        nutrition: { calories: 150, protein: 0, carbs: 40, fat: 0 }
    }
];

export const INITIAL_BADGES: Badge[] = [
    { id: 'b-01', name: 'First Fry', description: 'Placed your first order!', icon: '🍟', unlocks: null },
    { id: 'b-02', name: 'Loaded Legend', description: 'Tried all loaded fry varieties.', icon: '🏆', unlocks: 'Crown' },
    { id: 'b-03', name: 'Spud Saver', description: 'Used Spud Points for a discount.', icon: '💰', unlocks: null },
    { id: 'b-04', name: 'Night Owl', description: 'Ordered after 10 PM.', icon: '🦉', unlocks: 'Top Hat' },
];

export const INITIAL_PROMO_CODES: PromoCode[] = [
    { code: 'SAVE10', discountPercentage: 10, isActive: true },
    { code: 'POTATO20', discountPercentage: 20, isActive: true },
];

export const POTATO_AVATAR_ACCESSORIES: Record<string, string> = {
    'Crown': '👑',
    'Top Hat': '🎩',
    'Chef Hat': '👨‍🍳',
    'Sunglasses': '😎'
};

export const INITIAL_GALLERY_IMAGES: GalleryImage[] = [
    { id: 'g-01', url: 'https://picsum.photos/seed/food-1/800/600', caption: 'Our signature Volcano Fries' },
    { id: 'g-02', url: 'https://picsum.photos/seed/interior-1/600/800', caption: 'Cozy and modern dining area' },
    { id: 'g-03', url: 'https://picsum.photos/seed/food-2/800/600', caption: 'Freshly made Garden Delight' },
    { id: 'g-04', url: 'https://picsum.photos/seed/exterior-1/800/600', caption: 'Welcome to Potato & Friends' },
    { id: 'g-05', url: 'https://picsum.photos/seed/drinks-1/600/800', caption: 'Refreshing house-made lemonade' },
    { id: 'g-06', url: 'https://picsum.photos/seed/interior-2/800/600', caption: 'Smiles and good times' },
    { id: 'g-07', url: 'https://picsum.photos/seed/food-3/600/800', caption: 'A closeup of cheesy goodness' },
    { id: 'g-08', url: 'https://picsum.photos/seed/team-1/800/600', caption: 'Our amazing team' },
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
    {
        id: 'tm-01',
        name: 'Pawan Gurung',
        role: 'Executive Chef & Founder',
        bio: 'With a passion for potatoes and a flair for flavor, Pawan is the creative force behind every dish.',
        imageUrl: 'https://picsum.photos/seed/chef-pawan/400/400'
    }
];

export const INITIAL_RESERVATIONS: Reservation[] = [];